// <auto-generated />
using Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Entities.Migrations
{
    [DbContext(typeof(ChocolateContext))]
    [Migration("20211008220645_Inita")]
    partial class Inita
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Entities.Chocolate", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("OrigemCacau")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("PercentualAcucar")
                        .HasColumnType("real");

                    b.Property<float>("PercentualCacau")
                        .HasColumnType("real");

                    b.Property<float>("PercentualLeite")
                        .HasColumnType("real");

                    b.Property<float>("PercentualManteiga")
                        .HasColumnType("real");

                    b.Property<bool>("Temperado")
                        .HasColumnType("bit");

                    b.Property<int>("Temperatura")
                        .HasColumnType("int");

                    b.Property<string>("Tipo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Chocolates");
                });

            modelBuilder.Entity("Entities.Factory.Embalagem", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<float>("Altura")
                        .HasColumnType("real");

                    b.Property<float>("Largura")
                        .HasColumnType("real");

                    b.Property<string>("Material")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("EmbbEmbalagems");
                });

            modelBuilder.Entity("Entities.Factory.Produto", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ChocolateId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("EmbalagemId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ChocolateId");

                    b.HasIndex("EmbalagemId");

                    b.ToTable("Produtos");
                });

            modelBuilder.Entity("Entities.Factory.Produto", b =>
                {
                    b.HasOne("Entities.Chocolate", "Chocolate")
                        .WithMany()
                        .HasForeignKey("ChocolateId");

                    b.HasOne("Entities.Factory.Embalagem", "Embalagem")
                        .WithMany()
                        .HasForeignKey("EmbalagemId");

                    b.Navigation("Chocolate");

                    b.Navigation("Embalagem");
                });
#pragma warning restore 612, 618
        }
    }
}
